# Generated by Django 4.0.2 on 2022-02-19 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^20[2-9][0-9]-[0-1][0-9]-[0-3][0-9]$', message='Date must be YYYY-MM-DD, after 2020.')]),
        ),
    ]
